{% set name = "xwebrtc" %}
{% set version = "0.6.0" %}
{% set sha256 = "2d4fd7e529ed573f7abf793f0857033096ae6e2c8d58fbb9bf58fff114fae9b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xwebrtc/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - xeus >=0.24.1,<26
    - xtl >=0.6.8,<0.7
    - xproperty >=0.10.0,<0.11
    - xwidgets >=0.23.0,<0.25

test:
  commands:
    - test -d ${PREFIX}/include/xwebrtc  # [unix]
    - test -f ${PREFIX}/include/xwebrtc/xchat.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwebrtc/xwebrtcConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwebrtc/xwebrtcConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwebrtc\xchat.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwebrtcConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwebrtcConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ backend for the jupyter webrtc widget'
  dev_url: https://github.com/QuantStack/xwebrtc

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
