{% set name = "xwebrtc" %}
{% set version = "0.4.0" %}
{% set sha256 = "36a2386cd5369df4606d53b5dfd06930bcb61d3e13e6289b54e3cfd53ef1464a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xwebrtc/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  {% if 'toolchain' in compiler('cxx') %}skip: True{% endif %}  # Only build with modern compilers.
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xeus >=0.17.0,<0.18
    - xtl >=0.5.0,<0.6
    - xproperty >=0.7.0,<0.8
    - xwidgets >=0.15.0,<0.16

test:
  commands:
    - test -d ${PREFIX}/include/xwebrtc  # [unix]
    - test -f ${PREFIX}/include/xwebrtc/xchat.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwebrtc/xwebrtcConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwebrtc/xwebrtcConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwebrtc\xchat.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwebrtcConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwebrtcConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ backend for the jupyter webrtc widget'
  dev_url: https://github.com/QuantStack/xwebrtc

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
